 CREATE TABLE account (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    document_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaction (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    account_id INT,
    amount DECIMAL(15, 2) NOT NULL,
    operation_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES account(id)
);